# Jekyll config
title: David Vázquez
disqus: davazp
paginate: 4
exclude: ["generate.el", "org"]
auto: true
root: http://davazp.github.com

author:
  name: David Vázquez
  email: davazp@gmail.com
  github: davazp
